### ISSUE TITLE
[BUG] GUI layout slightly broken under windows if the display scaling is not 100%

### ISSUE THREAD

**Issue by Tillsten** [kevin-robben/model-fitting#3]
When not using 100% scaling the feedback box is overlaying with the settings.

**Comment by kevin-robben** [comment]
Till,

Thanks for your feedback. This was an issue with MATLAB App Designer. You'll notice my app initially defaults to 100% scaling because that's the best I could do at the time.

I've updated the Windows installer using a newer version of MATLAB and App Designer (2022a). The scaling issue appears to be fixed now. Let me know if you find otherwise. I'm not sure when I'll get around to updating the Mac installer as I have to borrow someone else's to do that. 

Kevin
